name: CI

on:
  push:
    branches:
      - 'feature/*'
      - 'update/*'
  pull_request:
    branches:
      - '*'

jobs:
  testsuite:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.3', '7.4', '8.0', '8.1']
    name: PHP ${{ matrix.php-version }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl, pdo_sqlite
        coverage: none

    - name: Composer install
      run: |
        if [[ ${{ matrix.php-version }} == '8.1' ]]; then
          composer update --ignore-platform-reqs
        else
          composer update
        fi
        composer run-script post-install-cmd --no-interaction

    - name: Run PHPUnit
      run: |
        cp config/app_local.example.php config/app_local.php
        vendor/bin/phpunit --verbose
      env:
        DATABASE_TEST_URL: sqlite://./testdb.sqlite

  coding-standard:
    strategy:
      fail-fast: false
      matrix:
        php-version: ['7.3', '7.4', '8.0', '8.1']
    name: Coding Standard - PHP ${{ matrix.php-version }}
    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, intl
        coverage: none

    - name: Composer install
      run: |
        if [[ ${{ matrix.php-version }} == '8.1' ]]; then
          composer update --ignore-platform-reqs
        else
          composer update
        fi
        composer run-script post-install-cmd --no-interaction

    - name: Run PHP CodeSniffer
      run: composer cs-check